# -*- coding: utf-8 -*-
"""blackjack MLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZUzojPa6Q81zKi79apwID-sY603Ue997
"""

# Adapted from Lecture 8 Code

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from sklearn.metrics import accuracy_score
import pandas as pd

#Upload the blkjckhands.csv file(from kaggle) to google collab
df = pd.read_csv('blkjckhands.csv')

# Filter out rows where 'winloss' is 'Push'
df = df[df['winloss'] != 'Push']

#Using a dictionary made adapting from the iris set program easier
madeUpData = {
    #Uses the pandas dataframe to assign the 3 columns as a nested list
    #card1, card2, dealcard1

    'data': df[['card1', 'card2', 'dealcard1']][0:10000].values.tolist(),
    #If we want to give the NN access to the dealers second card
    #'data': df[['card1', 'card2', 'dealcard1', 'dealcard2']][0:10000].values.tolist(),

    #Uses the pandas dataframe to assign the output index column
    #Replaces "Loss" with 0 and "Win" with 1 to actually use the classes
    'target': df['winloss'][0:10000].replace({'Loss': 0, 'Win': 1}).values.tolist()
}

X, y = madeUpData['data'], madeUpData['target'] ## Dataset Size X 3 ## Dataset Size X 1



                                                     ## 20% of the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train) # uses mean and standard deviation of the data to move the data
X_test = scaler.transform(X_test)

X_train = torch.tensor(X_train, dtype = torch.float32)
y_train = torch.tensor(y_train, dtype = torch.long)
X_test = torch.tensor(X_test, dtype = torch.float32)
y_test = torch.tensor(y_test, dtype = torch.long) # Long used because other functions will be expecting it

class MLP(nn.Module):
  def __init__(self, input_size, hidden_size, num_classes):
    super().__init__()
    self.fc1 = nn.Linear(input_size, hidden_size)
    self.relu = nn.ReLU()
    self.fc2 = nn.Linear(hidden_size, num_classes)

  def forward(self, x):
    out = self.fc1(x)
    out = self.relu(out)
    out = self.fc2(out)
    return out

input_size = X_train.shape[1] # 3
hidden_size = 8 # just left this number for now
num_classes = 2 # win/loss
model = MLP(input_size, hidden_size, num_classes)

criterion = nn.CrossEntropyLoss()

#Adam optimizer with a learning rate of 0.001
optimizer = optim.Adam(model.parameters(), lr = 0.001)

batch_size = 16
train_dataset = TensorDataset(X_train, y_train)
train_loader = DataLoader(train_dataset, batch_size = batch_size, shuffle = True)

#30 epochs was randomly assigned for now but seems to give similar results to 100
num_epochs = 30
for epoch in range(num_epochs):
  for batch_X, batch_y in train_loader: # Process each batch separately

    # Forward pass
    outputs = model(batch_X)
    loss = criterion(outputs, batch_y)
    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  if (epoch+1) % 10 == 0:
    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')
with torch.no_grad():
  outputs = model(X_test)
  _, predicted = torch.max(outputs, 1)

accuracy = accuracy_score(y_test, predicted)
print(f'Accuracy: {accuracy * 100:.2f}%')

#User input
card1 = int(input("What is your first card: "))
card2 = int(input("What is your second card: "))
dealerCard = int(input("What is the dealers face up card: "))

user_input = torch.tensor([[card1, card2, dealerCard]], dtype = torch.float32)
user_input = scaler.transform(user_input)
user_input = torch.tensor(user_input, dtype = torch.float32)

with torch.no_grad():
  #puts the users input into the model
  outputs = model(user_input)
  _, predicted = torch.max(outputs, 1)

#output is based on what the model predicted
if predicted == 0:
  print("You likely lose")
else:
  print("You likely win")
/*
#Little test for pandas
import pandas as pd

df = pd.read_csv('blkjckhands.csv')

combined_row_data = df['winloss'].values.tolist()
print(combined_row_data[0:10])

combined_row_data = df['winloss'].replace({'Loss': 0, 'Win': 1}).values.tolist()
print(combined_row_data[0:10])

#More testing
import pandas as pd

df = pd.read_csv('blkjckhands.csv')

#'card1', 'card2', 'dealcard1'
data = df[['card1', 'card2', 'dealcard1']][0:1000].values.tolist()

print(data[0:20])
*/